// <auto-generated />
using System;
using MiareFinancial.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(MiareFinancialContext))]
    [Migration("20221221141732_newQueries")]
    partial class newQueries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("MiareFinancial.Models.Courier.CourierGuarantee", b =>
                {
                    b.Property<int>("CourierGuaranteeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuaranteeAmount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourierGuaranteeId");

                    b.ToTable("CourierGuarantees");
                });

            modelBuilder.Entity("MiareFinancial.Models.Courier.CourierPunishmentDebt", b =>
                {
                    b.Property<int>("CourierPunishmentDebtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Amount")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LedgerId")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(2);

                    b.Property<string>("LedgerName")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(0);

                    b.HasKey("CourierPunishmentDebtId");

                    b.ToTable("CourierPunishmentDebts");
                });

            modelBuilder.Entity("MiareFinancial.Models.Courier.CourierScalableBonus", b =>
                {
                    b.Property<int>("CourierScalableBonusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LedgerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LedgerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourierScalableBonusId");

                    b.ToTable("CourierScalableBonuss");
                });

            modelBuilder.Entity("MiareFinancial.Models.Courier.CourierShiftIncome", b =>
                {
                    b.Property<int>("CourierShiftIncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourierShiftIncomeId");

                    b.ToTable("CourierShiftIncomes");
                });

            modelBuilder.Entity("MiareFinancial.Models.Trip.TripCourierSalary", b =>
                {
                    b.Property<int>("TripCourierSalaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FinalSalary")
                        .HasColumnType("REAL");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TripCourierSalaryId");

                    b.ToTable("TripCourierSalarys");
                });

            modelBuilder.Entity("MiareFinancial.Models.Trip.TripCourseCount", b =>
                {
                    b.Property<int>("TripCourseCountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CourseCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TripCourseCountId");

                    b.ToTable("TripCourseCounts");
                });

            modelBuilder.Entity("MiareFinancial.Models.Trip.TripDiscount", b =>
                {
                    b.Property<int>("TripDiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TripDiscountAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("TripVoucheAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TripDiscountId");

                    b.ToTable("TripDiscounts");
                });

            modelBuilder.Entity("MiareFinancial.Models.Trip.TripFinancial", b =>
                {
                    b.Property<int>("TripFinancialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClientHarshAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CourseCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DriverHarshAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FinalPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FinalSalary")
                        .HasColumnType("INTEGER");

                    b.HasKey("TripFinancialId");

                    b.ToTable("TripFinancials");
                });

            modelBuilder.Entity("MiareFinancial.Models.Trip.TripVendorFinalPrice", b =>
                {
                    b.Property<int>("TripVendorFinalPriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FinalPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TripVendorFinalPriceId");

                    b.ToTable("TripVendorFinalPrices");
                });

            modelBuilder.Entity("MiareFinancial.Models.Trip.TripVendorHarsh", b =>
                {
                    b.Property<int>("TripVendorHarshId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TripClientHarshAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TripVendorHarshId");

                    b.ToTable("TripVendorHarshs");
                });

            modelBuilder.Entity("MiareFinancial.Models.Vendor.VendorClientPaymentPayback", b =>
                {
                    b.Property<int>("VendorClientPaymentPaybackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LedgerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LedgerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VendorClientPaymentPaybackId");

                    b.ToTable("VendorClientPaymentPaybacks");
                });

            modelBuilder.Entity("MiareFinancial.Models.Vendor.VendorConcurrencyDiscount", b =>
                {
                    b.Property<int>("VendorConcurrencyDiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DailyDiscountAmount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndDateTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("PeriodDiscountAmount")
                        .HasColumnType("REAL");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VendorConcurrencyDiscountId");

                    b.ToTable("VendorConcurrencyDiscounts");
                });

            modelBuilder.Entity("MiareFinancial.Models.Vendor.VendorConcurrencyIncome", b =>
                {
                    b.Property<int>("VendorConcurrencyIncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DiscountAmount")
                        .HasColumnType("REAL");

                    b.Property<double?>("Income")
                        .HasColumnType("REAL");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VendorConcurrencyIncomeId");

                    b.ToTable("VendorConcurrencyIncomes");
                });

            modelBuilder.Entity("MiareFinancial.Models.Vendor.VendorMiscExpense", b =>
                {
                    b.Property<int>("VendorMiscExpenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VendorMiscExpenseId");

                    b.ToTable("VendorMiscExpenses");
                });

            modelBuilder.Entity("MiareFinancial.Models.Vendor.VendorSLAPayback", b =>
                {
                    b.Property<int>("VendorSLAPaybackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VendorSLAPaybackId");

                    b.ToTable("VendorSLAPaybacks");
                });

            modelBuilder.Entity("MiareFinancial.Models.Vendor.VendorSameServicePayback", b =>
                {
                    b.Property<int>("VendorSLAPaybackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Amount")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Week")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VendorSLAPaybackId");

                    b.ToTable("VendorSameServicePaybacks");
                });
#pragma warning restore 612, 618
        }
    }
}
