// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StatementModel.DAL;

#nullable disable

namespace app.Migrations.MiareStatement
{
    [DbContext(typeof(MiareStatementContext))]
    partial class MiareStatementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("StatementModel.Model.Courier.CourierPL", b =>
                {
                    b.Property<int>("CourierPLId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllWeekInMonth")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CourierDistibution")
                        .HasColumnType("REAL");

                    b.Property<double?>("CourierReactivationCost")
                        .HasColumnType("REAL");

                    b.Property<double?>("CourierRefferalCost")
                        .HasColumnType("REAL");

                    b.Property<double?>("Guarantee")
                        .HasColumnType("REAL");

                    b.Property<double?>("HurryTripCost")
                        .HasColumnType("REAL");

                    b.Property<double?>("NewCourierAcquisitionCost")
                        .HasColumnType("REAL");

                    b.Property<double?>("RevokeTripCost")
                        .HasColumnType("REAL");

                    b.Property<int>("ShareInMonth")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ShiftSales")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalCourierAcquisitionCost")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalDebt")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalTripIncentiveCost")
                        .HasColumnType("REAL");

                    b.Property<double?>("TripFarAssignCost")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Week")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeekJalali")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CourierPLId");

                    b.ToTable("CourierPLs");
                });

            modelBuilder.Entity("StatementModel.Model.Trip.TripPL", b =>
                {
                    b.Property<int>("TripPLId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllWeekInMonth")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CourierCPO")
                        .HasColumnType("REAL");

                    b.Property<double?>("CourierTripOnlySalary")
                        .HasColumnType("REAL");

                    b.Property<int?>("CourseCount")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("HarshBalanceIncome")
                        .HasColumnType("REAL");

                    b.Property<int>("ShareInMonth")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("TotalRealTripBalance")
                        .HasColumnType("REAL");

                    b.Property<double?>("TripDiscountCredit")
                        .HasColumnType("REAL");

                    b.Property<double?>("TripDiscountVoucher")
                        .HasColumnType("REAL");

                    b.Property<double?>("VendorCPO")
                        .HasColumnType("REAL");

                    b.Property<double?>("VendorFinalPrice")
                        .HasColumnType("REAL");

                    b.Property<double?>("VendorHarsh")
                        .HasColumnType("REAL");

                    b.Property<double?>("VendorMiscExpense")
                        .HasColumnType("REAL");

                    b.Property<double?>("VendorTotalCPO")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Week")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeekJalali")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TripPLId");

                    b.ToTable("TripPLs");
                });

            modelBuilder.Entity("StatementModel.Model.Vendor.VendorCDWeekly", b =>
                {
                    b.Property<int>("VendorCDWeeklyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllWeekInMonth")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ConcurrencyDiscount")
                        .HasColumnType("REAL");

                    b.Property<int>("ShareInMonth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Week")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeekJalali")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VendorCDWeeklyId");

                    b.ToTable("VendorCDWeeklys");
                });

            modelBuilder.Entity("StatementModel.Model.Vendor.VendorPL", b =>
                {
                    b.Property<int>("VendorPLId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllWeekInMonth")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ConcurrencyDiscount")
                        .HasColumnType("REAL");

                    b.Property<double?>("ConcurrencySales")
                        .HasColumnType("REAL");

                    b.Property<int>("ShareInMonth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Week")
                        .HasColumnType("TEXT");

                    b.Property<string>("WeekJalali")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VendorPLId");

                    b.ToTable("VendorPLs");
                });
#pragma warning restore 612, 618
        }
    }
}
